name: common-review

on:
  workflow_call:
    inputs:
      config-path:
        description: 'Path to the files to lint'
        required: true
        type: string
    secrets:
      github_token:
        description: 'GitHub Token'
        required: true

jobs:
  lint-and-review:
    name: Lint and Review with textlint and reviewdog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: npm install

      - name: Run textlint
        run: npx textlint "${{ inputs.config-path }}" --format checkstyle > textlint-report.xml || true

      - name: Run textlint with fix
        run: npx textlint --fix "${{ inputs.config-path }}" || true

      - name: Generate diff
        run: git diff > textlint-report.diff

      - name: Debug textlint report
        run: cat textlint-report.xml

      - name: Debug diff report
        run: cat textlint-report.diff

      - name: Install reviewdog
        run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Run reviewdog for diff suggestions
        run: |
          reviewdog -f=diff \
          -name="textlint-suggester" \
          -reporter=github-pr-review \
          -level=warning \
          -filter-mode=added \
          -fail-on-error=false \
          < textlint-report.diff
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}

      - name: Run reviewdog for textlint errors
        run: |
          reviewdog -f=checkstyle \
          -name="textlint-errors" \
          -reporter=github-pr-review \
          -level=warning \
          -filter-mode=added \
          -fail-on-error=false \
          < textlint-report.xml
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}

