name: reviewdog
on: [pull_request]
jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node/npm
        uses: actions/setup-node@v3

      # package-lock.json生成のため、npm installを実行する
      - name: Install Dependencies
        run: npm install

      # キャッシュ取得
      - name: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.GA_REVEIWDOG_TOKEN }}
          reporter: suggestion
          level: warning
          textlint_flags: "--diff '{book,articles}/**'"

