name: reviewdog

on:
  pull_request:
    branches:
      - main  # PRがトリガーされるブランチ
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: npm install

      - name: Run textlint
        run: npm run lint -- --format checkstyle -o textlint-report.xml || true

      - name: Debug textlint report
        run: cat textlint-report.xml

      - name: Reviewdog with PR Review
        uses: reviewdog/action-reviewdog@v1
        with:
          github_token: ${{ secrets.GA_REVEIWDOG_TOKEN }}
          tool_name: textlint
          level: warning
          reporter: github-pr-review
          filter_mode: added
          fail_on_error: false
          reviewdog_flags: "-f=checkstyle < textlint-report.xml"

      - name: Reviewdog Suggester
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.GA_REVEIWDOG_TOKEN }}
          tool_name: textlint
          level: warning

