name: reviewdog-comments

on:
  pull_request:
    branches:
      - main  # PRがトリガーされるブランチ
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: npm install

      - name: Run textlint
        run: npx textlint articles/**/*.md --format checkstyle > textlint-report.xml || true

      - name: Debug textlint report
        run: cat textlint-report.xml

      - name: Install reviewdog
        run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Run reviewdog for textlint errors
        run: |
          reviewdog -f=checkstyle \
          -name="textlint" \
          -reporter=github-pr-review \
          -level=warning \
          -filter-mode=added \
          -fail-on-error=false \
          < textlint-report.xml
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

