name: reviewdog-suggester

on:
  pull_request:
    branches:
      - main  # PRがトリガーされるブランチ
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: npm install

      - name: Run textlint
        run: npx textlint --fix articles/**/*.md || true

      - name: Generate diff
        run: git diff > textlint-report.diff

      - name: Debug textlint report
        run: cat textlint-report.diff

      - name: Run reviewdog suggester
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: textlint
          level: warning
          filter_mode: diff_context
          cleanup: true

