name: reviewdog

on:
  pull_request:
    branches:
      - main  # PRがトリガーされるブランチ
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: npm install

      - name: Run textlint
        run: npx textlint articles/**/*.md > textlint-errors.txt || true

      - name: Run textlint with fix
        run: npx textlint --fix articles/**/*.md || true

      - name: Generate diff
        run: git diff > textlint-report.diff

      - name: Debug textlint report
        run: cat textlint-report.diff

      - name: Debug textlint errors
        run: cat textlint-errors.txt

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run reviewdog with PR Review for Suggestions
        run: |
          reviewdog -f=diff \
          -name="textlint" \
          -reporter=github-pr-review \
          -level=warning \
          -filter-mode=added \
          -fail-on-error=false \
          < textlint-report.diff
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run reviewdog with PR Review for Errors
        run: |
          reviewdog -efm="%f:%l:%c: %m" \
          -name="textlint-errors" \
          -reporter=github-pr-review \
          -level=warning \
          -filter-mode=added \
          -fail-on-error=false \
          < textlint-errors.txt
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

